name: C/C++ CI

on:
  push:
    branches: [ Linux_Defender_for_Ubuntu_Main-dev ]
  pull_request:
    branches: [ Linux_Defender_for_Ubuntu_Main-dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
